#!/bin/bash
if [ $# -eq 0 ]; then
	echo "Setup DNSSEC for a zone"
	echo
	echo "usage: ${0} zone"
	echo
	exit 1
fi
zone="${1}"
cd /var/named/
dnssec-keygen -r /dev/urandom -a NSEC3RSASHA1 -b 2048 -n ZONE ${zone}
dnssec-keygen -r /dev/urandom -f KSK -a NSEC3RSASHA1 -b 4096 -n ZONE ${zone}
echo "*********************************************"
echo "* The following goes into your parent zone: *"
echo "*********************************************"
cat "dsset-${zone}."

